#!/usr/bin/env python3
"""One-time Google Calendar OAuth consent flow -- manual copy-paste variant.

Run this ONCE to authorize Pocket CFO's Calendar agent to create events in your
REAL Google Calendar via the standard Calendar v3 API -- no Workspace Developer
Preview needed (that is only required for the hosted Calendar MCP endpoint;
this is the plain, GA Calendar API instead).

WHY MANUAL COPY-PASTE, NOT A LOCAL SERVER: the "normal" desktop OAuth flow spins
up a local HTTP server and waits for the browser to redirect back to it. On WSL2,
that redirect can hit "ERR_CONNECTION_REFUSED" even though the server is correctly
listening inside WSL2 -- the Windows<->WSL2 localhost port-forwarding proxy does
not reliably forward every ephemeral port. This script sidesteps that entirely: it
uses a bare "http://localhost" redirect URI (no port, matching what a Desktop-app
OAuth client is registered with) and asks you to paste back the URL you land on --
no listener, no port, no forwarding dependency at all.

Prerequisites (one-time, in Cloud Console for your GCP project):
  1. APIs & Services -> Library -> enable "Google Calendar API".
  2. APIs & Services -> OAuth consent screen -> configure it if you haven't
     already (External is fine; add your own email as a test user).
  3. APIs & Services -> Credentials -> Create Credentials -> OAuth client ID ->
     Application type: "Desktop app" -> Create -> Download JSON.
  4. Save that downloaded file as: app/data/calendar_client_secret.json
     (gitignored -- never commit it).

Usage (two steps):
    uv run python scripts/calendar_oauth_setup.py start
        Prints an authorization URL. Visit it, sign in, click Allow. You will
        land on a page that FAILS TO LOAD (localhost with nothing listening) --
        that's expected. Copy the full URL from your browser's address bar; it
        contains "?code=...&state=...".

    uv run python scripts/calendar_oauth_setup.py finish "<pasted URL>"
        Completes the exchange and saves app/data/calendar_token.json (gitignored).
        A bare authorization code also works instead of the full URL.

After `finish` succeeds, the Calendar agent's `sync_money_dates_to_calendar` tool
uses the saved token automatically -- no further browser interaction needed
(tokens auto-refresh).
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path
from urllib.parse import parse_qs, urlparse

from app.tools.calendar_api import CALENDAR_SCOPES, CLIENT_SECRET_PATH, TOKEN_PATH

# Google commonly returns a broader granted-scope set than requested (e.g. it
# folds in a scope granted in an earlier consent, via include_granted_scopes).
# oauthlib treats ANY scope mismatch as fatal by default; this relaxes that check
# to a no-op, since a superset of what we asked for is fine for our purposes.
os.environ.setdefault("OAUTHLIB_RELAX_TOKEN_SCOPE", "1")

# Ephemeral: holds the PKCE code_verifier generated by `start` so `finish` (a
# separate process invocation) can complete the same authorization flow.
_STATE_PATH = Path("app/data/.calendar_oauth_state.json")


def _build_flow():
    from google_auth_oauthlib.flow import Flow

    flow = Flow.from_client_secrets_file(
        str(CLIENT_SECRET_PATH), scopes=CALENDAR_SCOPES
    )
    # No port: matches a Desktop-app client's registered "http://localhost" exactly,
    # and needs no listening socket at all (see module docstring for why).
    flow.redirect_uri = "http://localhost"
    return flow


def start() -> None:
    if not CLIENT_SECRET_PATH.exists():
        raise SystemExit(
            f"Missing {CLIENT_SECRET_PATH}.\n\n"
            "Download your Desktop-app OAuth client JSON from Google Cloud Console "
            "and save it at that exact path first -- see this script's docstring."
        )
    flow = _build_flow()
    auth_url, state = flow.authorization_url(
        access_type="offline", include_granted_scopes="true", prompt="consent"
    )
    _STATE_PATH.parent.mkdir(parents=True, exist_ok=True)
    _STATE_PATH.write_text(
        json.dumps({"code_verifier": flow.code_verifier, "state": state}),
        encoding="utf-8",
    )
    print("\nVisit this URL, sign in, and click Allow:\n")
    print(auth_url)
    print(
        "\nThe page you land on afterward will likely fail to load -- that's "
        "expected (nothing is listening on localhost). Copy the FULL URL from "
        "your browser's address bar and run:\n"
    )
    print('  uv run python scripts/calendar_oauth_setup.py finish "<pasted URL>"')


def finish(pasted: str) -> None:
    if not _STATE_PATH.exists():
        raise SystemExit("Run 'start' first (see this script's docstring).")
    saved = json.loads(_STATE_PATH.read_text())

    flow = _build_flow()
    flow.code_verifier = saved["code_verifier"]

    code = pasted.strip()
    if code.startswith("http"):
        qs = parse_qs(urlparse(code).query)
        found = qs.get("code", [None])[0]
        if not found:
            raise SystemExit(
                "Couldn't find '?code=...' in that URL. Paste the full address-bar URL."
            )
        code = found

    flow.fetch_token(code=code)
    creds = flow.credentials

    TOKEN_PATH.parent.mkdir(parents=True, exist_ok=True)
    TOKEN_PATH.write_text(creds.to_json(), encoding="utf-8")
    _STATE_PATH.unlink(missing_ok=True)  # one-time use; PKCE verifier no longer needed
    print(f"\nAuthorized. Token saved to {TOKEN_PATH}")


def main() -> None:
    if len(sys.argv) < 2 or sys.argv[1] not in ("start", "finish"):
        raise SystemExit(__doc__)
    if sys.argv[1] == "start":
        start()
    else:
        if len(sys.argv) < 3:
            raise SystemExit('Usage: ... finish "<pasted URL or code>"')
        finish(sys.argv[2])


if __name__ == "__main__":
    main()
